spring:
  application:
    name: employee-management-service
  datasource:
    url: jdbc:mysql://localhost:3306/employee_management
    username: root
    password: altir
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}

# Allow fn-db to create new related entities (like User) when ID is not specified
fn:
  data:
    access:
      mapping:
        createToOneReferencesIfRequired: true

# Keycloak
keycloak:
  auth-server-url: http://localhost:8180
  realm: employee-management
  client-id: employee-management-service
  client-secret: Dlh1NajE90pEBIwpI0nuhY9ZsOvlnGgq
